config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:create]
    post "/favourite", to: "events#favourite"
    delete "/unfavourite", to: "events#unfavourite"
  end

  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end

  resources :chatrooms, only: [:index, :show ] do
    resources :messages, only: :create
  end

  resources :studios, only: [:new, :show, :create, :edit, :update] do
    resources :events, only: [:create]
    resources :chatrooms, only: [:create]
  end

  get '/dashboard', to: 'pages#dashboard'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_card_category.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  Breakfast
</div>

app/views/shared/_card_event.html.erb
<div class="card-event">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-event-infos">
    <h2>Product name</h2>
    <p><em>by Studio_Name</em></p>
    <p><i class="fas fa-user-friends"></i> 10 / 15</p>
    <p>21 March 2022, 6:00 AM - 7:00 AM</p>
  </div>
  <div class="card-event-price">
    <strong>IDR 100K</strong>
  </div>
</div>

app/views/shared/_card_package.html.erb
<div class="card-package">
  <h3>Ten-Classes Package</h3>
  <div class="card-package-price">
    <h2>IDR 80K</h2>
    <p>per session</p>
  </div>
  <p>Valid for 1 months</p>
  <%= link_to "Buy Now", "#", class: "btn-secondary" %>
</div>
<div class="card-package-middle">
  <h3>Twenty-Classes Package</h3>
  <div class="card-package-price">
    <h2>IDR 70K</h2>
    <p>per session</p>
  </div>
  <p>Valid for 3 months</p>
  <%= link_to "Buy Now", "#", class: "btn-secondary" %>
</div>
<div class="card-package">
  <h3>Fifteen-Classes Package</h3>
  <div class="card-package-price">
    <h2>IDR 75K</h2>
    <p>per session</p>
  </div>
  <p>Valid for 2 months</p>
  <%= link_to "Buy Now", "#", class: "btn-secondary" %>
</div>

app/views/shared/_card_review.html.erb
<div class="card-review">
  <h2>Product name</h2>
  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis optio delectus molestiae rem in? Minus consectetur ab nam sapiente hic, necessitatibus cum labore ipsum similique quia nemo blanditiis officia sit!</p>
  <div class="card-review-stars">
    <span class="fa fa-star icon-star"></span>
    <span class="fa fa-star icon-star"></span>
    <span class="fa fa-star icon-star"></span>
    <span class="fa fa-star icon-star"></span>
    <span class="fa fa-star icon-star"></span>
  </div>
</div>

app/views/shared/_card_review_large.html.erb
<div class="d-flex justify-content-center mt-4">
  <div class="card-review-large">
    <div>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
    </div>
    <p>I'm so greatful I found WOW! This is the best when you want to find a workout session!</p>
    <%= image_tag "andrey.jpg", class: "avatar-medium dropdown-toggle" %>
    <p>Andrey</p>
  </div>
    <div class="card-review-large">
    <div>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-empty"></span>
    </div>
    <p>The platform is very well-structured and this makes it easy to use!</p>
    <%= image_tag "nasimul.jpeg", class: "avatar-medium dropdown-toggle" %>
    <p>Nasimul</p>
  </div>
    <div class="card-review-large">
    <div>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
    </div>
    <p>Such a great site! Nice straightforward system to use! It just made my day easier!</p>
    <%= image_tag "pooja.jpeg", class: "avatar-medium dropdown-toggle" %>
    <p>Pooja</p>
  </div>
    <div class="card-review-large">
    <div>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-star"></span>
      <span class="fa fa-star icon-empty"></span>
    </div>
    <p>WOW is the most AWESOME solution! this Has really helped me grow my business!</p>
    <%= image_tag "mel.jpeg", class: "avatar-medium dropdown-toggle" %>
    <p>Melike</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Site footer -->
<footer class="site-footer bg-dark text-center py-4">
  <h6>CONTACT US</h6>
  <ul class="social-icons mt-2 mb-1">
    <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
    <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
    <li><a class="instagram" href="#"><i class="fab fa-instagram"></i></a></li>
  </ul>
  <p class="copyright-text">&copy; 2022 Work Out Web</p>
</footer>

app/views/shared/_map.html.erb
<div id="map" style="width: 100%; height: 100vh;" class="<%= 'map-show' if action_name == 'show' && controller_name == "studios" %>"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-mapbox-avatar-value="<%= user_signed_in? ? current_user.avatar.service_url(crop: :fill, radius: :max) : "" %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-4 <%= 'navbar-home fixed-top' if action_name == 'home' %>" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "wow-logo.png" %>
    <% end %>

    <%= form_tag events_path, method: :get, class: action_name == "home" ? "d-none" : "" do %>
      <div class="row g-0" id="search">
        <div class="col-md-12">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a class"
          %>
        </div>
        <button class="btn-search"><i class="fas fa-search fa-2xs"></i></button>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown ms-2">
            <%= cl_image_tag current_user.avatar.key, height: 40, width: 40, crop: :fill, class: "avatar-small dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="notification border-0">
              <%=
                if (current_user && current_user.chatrooms)
                  @chatrooms = (current_user.chatrooms + Chatroom.where(studio: current_user.studios)).uniq
                  if (@chatrooms.count > 0)
                    unread = @chatrooms.map { |cr| cr.messages.select { |m| m.read == false && m.user != current_user }.count }.sum
                    unread if unread > 0
                  end
                end
              %>
            </div>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if !current_user.studios.empty? %>
                <%= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
                <%= link_to "Create new class", new_event_path, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Create a Studio", new_studio_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>