config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:create]
    post "/favourite", to: "events#favourite"
    delete "/unfavourite", to: "events#unfavourite"
  end

  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end

  resources :chatrooms, only: [:index, :show ] do
    resources :messages, only: :create
  end

  resources :studios, only: [:new, :show, :create, :edit, :update] do
    resources :events, only: [:create]
    resources :chatrooms, only: [:create]
  end

  get '/dashboard', to: 'pages#dashboard'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/event.rb
class Event < ApplicationRecord
  CATEGORIES = ["Yoga", "Surfing", "HIIT", "Boxing", "Weight-Lifting", "Crossfit", "Swimming", "Others"]
  LEVELS = ["Beginner", "Intermediate", "Advanced", "All Levels"]

  before_save :add_start_time_end_time_after_creation
  monetize :price_cents

  belongs_to :studio
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
  acts_as_favoritable

  validates :name, :category, :date, :time, :duration, :limit_attendees, :price, :instructor, :level, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :level, inclusion: { in: LEVELS }

  include PgSearch::Model
  pg_search_scope :search_by,
    against: [ :name, :category],
    associated_against: {
      studio: [ :name, :address ]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  private

  def add_start_time_end_time_after_creation
    d = self.date
    t = self.time
    self.start_time = DateTime.new(d.year, d.month, d.day, t.hour, t.min, t.sec, t.zone)
    self.end_time = self.start_time + self.duration.minutes
  end

end

app/controllers/events_controller.rb
require 'date'

class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @categories = Event::CATEGORIES

    if params[:query].present?
      @events = Event.search_by(params[:query])
    elsif params[:category].present?
      @events = Event.where(category: params[:category])
    else
      @events = Event
    end

    if params[:date].present?
      @events = @events.where(date: params[:date])
    end

    if params[:time].present?
      @events = @events.where(time: params[:time].to_time)
    end

    if params[:level].present?
      @events = @events.where(level: params[:level])
    end

    if params[:start_date].present?
      @events = @events.where('date > ?', params[:start_date])
    end

    @events = @events.where('start_time > ?', DateTime.now)

    @events_group = @events.group_by { |event| [event.date, event.time.strftime('%k:%M')] }.sort_by { |group| group[0] }
    @studios = Studio.where(id: @events.pluck(:studio_id))
    # the `geocoded` scope filters only studios with coordinates (latitude & longitude)

    @markers = @studios.geocoded.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        info_window: render_to_string(partial: "info_window", locals: { studio: studio }, formats: [:html]),
        image_url: helpers.asset_url("wow-logo.png")
      }
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'class_view', locals: { events: @events, events_group: @events_group }, formats: [:html] }
    end
  end

  def show
    @event = Event.find(params[:id])
    @studio = @event.studio
    @events = Event.where(studio: @studio)
    reviews = @studio.events.map {|event| event.reviews }
    @reviews = reviews.flatten
    @events_group = @events.group_by { |event| [event.date, event.time.strftime('%k:%M')] }.sort_by { |group| group[0] }
    @markers = [{
      lat: @studio.latitude,
      lng: @studio.longitude,
      info_window: render_to_string(partial: "events/info_window", locals: { studio: @studio }, formats: [:html]),
      image_url: helpers.asset_url("wow-logo.png")
    }] # marker for the current studio
    @chatroom = Chatroom.find_by(user: current_user, studio: @studio)
    if @chatroom.nil?
      @chatroom = Chatroom.new
      @chatroom.studio = @studio
      @chatroom.user = current_user
      @chatroom.save
    end
    @message = Message.new # input form
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.studio = current_user.studios.first
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(params[:event])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  end

  def favourite
    @event = Event.find(params[:event_id])
    current_user.favorite(@event)
    flash[:notice] = "Added to favourite"
    redirect_to event_path(@event)
  end

  def unfavourite
    @event = Event.find(params[:event_id])
    current_user.unfavorite(@event)
    flash[:notice] = "Removed from favorite"
    redirect_to event_path(@event)
  end


  private

  def event_params
    params.require(:event).permit(:name, :category, :date, :time, :duration, :limit_attendees,
      :price, :instructor, :level, :photo)
  end
end

app/views/events/_booking.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-black h-50">
        <%= image_tag "wow-logo.png", id:"icon" %>
        <h5 class="modal-title text-white" id="exampleModalLabel"><%= @event.name %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="card-image-modal" style="background-image: url( <%= cl_image_path @event.photo.key, height: 400, crop: :fill%>)"></div>
          <div class="modal-card lh-sm">
            <div class="item-details d-flex justify-content-center mt-3">
              <div class="p-2">
                <p><i class="fas fa-location-arrow"></i> </p>
                <p><i class="fas fa-calendar-alt"> </i></p>
                <p><i class="fas fa-user-friends"> </i> </p>
                <p><i class="fas fa-money-bill"> </i></p>
              </div>
              <div class="p-2">
                <p> <%= @event.studio.address %></p>
                <p> <%= @event.date.strftime("%e %b %Y") %>, <%= @event.time.strftime('%I:%M %p') %></p>
                <p> <%= @event.bookings.where.not(status: "Cancelled").count %> / <%= @event.limit_attendees %> Booked</p>
                <p> <%= humanized_money_with_symbol(@event.price) %></p>
              </div>
            </div>
          </div>
        </div>
      <div class="modal-footer">
        <%= link_to "Pay Now", event_bookings_path(@event, paynow: true), method: :post, class: "btn btn-primary w-100" %>
        <%= link_to "Pay Later", event_bookings_path(@event, paylater: true), method: :post, class: "btn btn-secondary w-100" %>
      </div>
    </div>
  </div>
</div>

app/views/events/_class_calendar.html.erb
<%= week_calendar(events: @events) do |date, _| %>
  <% event_grouped_by_time = @events.filter { |event| event.date == date }.group_by { |event| event.time.strftime('%k:%M') } %>
  <% event_grouped_by_time.each do |time, events_per_time| %>
    <div class="card-calendar-group">
      <p class="mb-1"><%= time %></p>
      <% events_per_time.each do |event_per_time| %>
        <%= link_to event_path(event_per_time) do %>
          <div class="card-calendar p-2">
            <%= cl_image_tag event_per_time.photo.key, width: "50px", height: "50px" %>
            <div>
              <p><strong><%= event_per_time.name %></strong></p>
              <p><em>by <%= event_per_time.studio.name %></em></p>
              <p><%= humanized_money_with_symbol(event_per_time.price) %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/events/_class_lists.html.erb
<div class="d-flex">
  <div class="container class-list my-2 px-4">
    <h2><%= pluralize events.count, "class" %> found</h2>
    <% events_group.each do |date_time, events| %>
    <div class="card-events mb-4">
      <p class="mb-1"><%= date_time[0].strftime("%e %b %Y") %>, <%= date_time[1] %></p>
      <hr class="mt-0">
      <% events.each do |event| %>
        <%= link_to event_path(event) do  %>
          <div class="card-event mx-2">
            <%= cl_image_tag event.photo.key %>
            <div class="card-event-infos">
              <h2><%= event.name %></h2>
              <p><em>by <%= event.studio.name %></em></p>
              <p><i class="fas fa-user-friends"></i> <%= event.bookings.where.not(status: "Cancelled").count %> / <%= event.limit_attendees %></p>
              <p><%= event.level %> Class</p>
            </div>
            <div class="card-event-price">
              <% if current_user && current_user.bookings.where.not(status: "Cancelled").pluck(:event_id).include?(event.id) %>
                <div class="card-event-status border-success bg-success">
                  Booked
                </div>
              <% elsif event.limit_attendees <= event.bookings.where.not(status: "Cancelled").count %>
                <div class="card-event-status border-info bg-info">
                  Class Full
                </div>
              <% else %>
                <div>
                </div>
              <% end %>
              <strong><%= humanized_money_with_symbol(event.price) %></strong>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
    <% if events.count >= 4 %>
      <div class="text-center">
        <button class="btn-round mx-auto" data-controller="navigation" data-action="click->navigation#scrollToTop"><i class="fas fa-arrow-up"></i></button>
      </div>
    <% end %>
  </div>
  <%= render 'shared/map' %>
</div>

app/views/events/_class_view.html.erb
<div class="tab-slider--container" data-filter-events-target="view">
  <div id="tab1" class="tab-slider--body <%= 'd-none' unless params[:list] == "true" || params[:calendar] != "true" %>" data-filter-events-target="listView">
    <%= render 'class_lists', events: events, events_group: events_group %>
  </div>
  <div id="tab2" class="tab-slider--body px-4 <%= 'd-none' unless params[:calendar] == "true" %>" data-filter-events-target="calendarView">
    <%= render 'class_calendar', events: events %>
  </div>
</div>

app/views/events/_info_window.html.erb
<div class="card-map">
<%= cl_image_tag studio.avatar.key, height: 40, width: 40, crop: :fill, class: "avatar-small" %>
  <h2><%= studio.name %></h2>
  <p><%= studio.address %></p>
  <div class="overflow-scroll hide-scrollbar">
  <% event_grouped_by_time = @events.where(studio: studio).group_by { |event| event.start_time.strftime('%a, %d %b - %k:%M') } %>
  <% event_grouped_by_time.each do |time, events_per_time| %>
    <div class="card-calendar-group">
      <p class="mb-1"><%= time %></p>
      <% events_per_time.each do |event_per_time| %>
        <%= link_to event_path(event_per_time) do %>
          <div class="card-calendar p-2">
            <%= cl_image_tag event_per_time.photo.key, width: "50px", height: "50px" %>
            <div>
              <p><strong><%= event_per_time.name %></strong></p>
              <p><%= humanized_money_with_symbol(event_per_time.price) %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container col-8 mb-5">
  <h3>Edit your class here</h3>
  <br>
  <%= simple_form_for @event do |f| %>
    <%= f.input :name %>
    <%= f.input :category, :required => false,
                collection: Event::CATEGORIES %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :duration %>
    <%= f.input :description %>
    <%= f.input :instructor %>
    <%= f.input :limit_attendees %>
    <%= f.input :level, collection: Event::LEVELS %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :price_cents %>
    <%= f.input :photo %>
    <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div>

app/views/events/index.html.erb
<div data-controller="filter-events">
  <div class="filters d-flex justify-content-between py-2 px-4" data-controller="filter" data-action="scroll@window->filter#updateFilter">
    <%= simple_form_for :event, url: events_path, method: :post, remote: true, html: { class:"filters d-flex text-white mb-0", data: { filter_events_target: 'form' } } do |f| %>
      <div class="form-group d-flex align-items-center me-4 justify-content-between">
        <%# <label for="field-1" class="col-sm-3 control-label">Category</label> %>
        <div class="d-flex align-items-center">
        <%= f.input :category, :required => false, selected: params[:category],
                      collection: Event::CATEGORIES, label: false, prompt: "Select Category",
                      input_html: { \
                        "data-filter-events-target": "inputCategory", \
                        "data-action": "change->filter-events#updateView" \
                      }
                    %>
        </div>
      </div>
      <div class="form-group d-flex align-items-center me-4 justify-content-between">
        <%# <label for="field-1" class="col-sm-3 control-label">Level</label> %>
        <div class="d-flex align-items-center">
        <%= f.input :level, :required => false, selected: params[:level],
                      collection: Event::LEVELS, label: false, prompt: "Select Level",
                      input_html: { \
                        "data-filter-events-target": "inputLevel", \
                        "data-action": "change->filter-events#updateView" \
                      }
                    %>
        </div>
      </div>
      <div class="form-group d-flex align-items-center me-4 justify-content-between">
        <%# <label for="field-1" class="col-sm-3 control-label">Date</label> %>
        <div class="d-flex align-items-center">
        <%= f.input :date, as: :date, :required => false, html5: true, label: false,
                    input_html: { \
                      "data-filter-events-target": "inputDate", \
                      "data-action": "input->filter-events#updateView" \
                    }
                  %>
        </div>
      </div>
      <div class="form-group d-flex align-items-center me-4 justify-content-between">
        <%# <label for="field-1" class="col-sm-3 control-label">Time</label> %>
        <div class="d-flex align-items-center">
        <%= f.input :time, as: :time, :required => false, html5: true, label: false,
                    input_html: {
                      "data-filter-events-target": "inputTime",
                      "data-action": "input->filter-events#updateView",
                      step: 1800
                    }
                  %>
        </div>
      </div>
    <% end %>
    <div>
      <div class="tab-slider--nav">
        <ul class="tab-slider--tabs <%= 'slide' if params[:calendar] == "true" %>" data-filter-events-target="tabs">
          <li class="tab-slider--trigger <%= 'active' if params[:list] == "true" || params[:calendar] != "true" %>" rel="tab1" data-filter-events-target="listButton" data-action="click->filter-events#swichTab"><i class="fa fa-list"></i></li>
          <li class="tab-slider--trigger <%= 'active' if params[:calendar] == "true" %>" rel="tab2" data-filter-events-target="calendarButton" data-action="click->filter-events#swichTab"><i class="fa fa-calendar-alt"></i></li>
        </ul>
      </div>
    </div>
  </div>
  <%= render 'class_view', events: @events, events_group: @events_group %>
</div>

app/views/events/new.html.erb
<div class="container col-8 mb-5">
  <h3>Create your class here</h3>
  <br>
  <%= simple_form_for @event do |f| %>
    <%= f.input :name %>
    <%= f.input :category, :required => false,
                collection: Event::CATEGORIES %>
    <%= f.input :date %>
    <%= f.input :time %>
    <%= f.input :duration %>
    <%= f.input :description %>
    <%= f.input :instructor %>
    <%= f.input :limit_attendees %>
    <%= f.input :level, collection: Event::LEVELS %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{@event.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @event.description %>
<% content_for :meta_image, cl_image_path(@event.photo.key) %>
<div class="container pb-5" data-controller="popup">
  <div class="card-wrapper align-items-end mt-5 mb-5">
    <div class="card-show h-100">
      <div class="card-image h-100" style="background-image: url( <%= cl_image_path @event.photo.key, height: 400, crop: :fill%>)"></div>
    </div>
    <div class="card-show h-100 d-flex flex-column justify-content-between">
      <div class="card-show-name">
        <h2><%= @event.name %> </h2>
        <p> <em> with <%= @event.instructor %></em></p>
        <div style="margin-top: -15px ">
          <span class="fa fa-star icon-star"></span>
          <span class="fa fa-star icon-star"></span>
          <span class="fa fa-star icon-star"></span>
          <span class="fa fa-star icon-empty"></span>
          <span class="fa fa-star icon-empty"></span>
        </div>
        <div class="mt-2">
        <p style="font-size: 30px"> <strong><%= humanized_money_with_symbol(@event.price) %></strong></p>
        </div>
      </div>
      <div class="d-flex">
          <%# <p><i class="fas fa-calendar-alt"></i></p> %>
          <p>  <%= @event.date.strftime("%e %b %Y") %>, <%= @event.time.strftime('%I:%M %p') %></p>
      </div>
      <div class="item-details d-flex">
        <div class="me-2">
          <p><i class="far fa-chart-bar"></i></i></p>
          <p><i class="fas fa-location-arrow"></i></p>
        </div>
        <div class="me-2">
          <p>  <%= @event.level %> Class</p>
          <p>  <%= @event.studio.address %></p>
        </div>
      <div class="item-value d-flex">
      <div class="me-2">
        <p><i class="far fa-hourglass"></i></p>
        <p><i class="fas fa-user-friends"></i> </p>
      </div>
        <div class="me-2">
          <p>  <%= @event.duration %> minutes</p>
          <p>  <%= @event.bookings.where.not(status: "Cancelled").count %> / <%= @event.limit_attendees %> Booked</p>
        </div>
      </div>
      </div>
          <div class="item-button">
            <% if current_user && current_user.bookings.where.not(status: "Cancelled").pluck(:event_id).include?(@event.id) %>
            <button type="button" class="btn btn-primary disabled border-success bg-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Booked
            <% elsif @event.limit_attendees <= @event.bookings.where.not(status: "Cancelled").count %>
            <button type="button" class="btn btn-primary disabled border-info bg-info" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Class Full
            <% else %>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Book Now
            <% end %>
          </button>
            <% if user_signed_in? %>
              <% if current_user.favorited?(@event) %>
                <%= link_to event_unfavourite_path(@event), method: :delete, remote: true do %>
                  <i style="color: red;" class="fas fa-heart fa-2x"></i>
                <% end %>
              <% else %>
                <%= link_to event_favourite_path(@event), method: :post, remote: true do %>
                  <i style="color: red;" class="far fa-heart fa-2x"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
      <!-- Modal -->
    <%= render 'booking' %>
    </div>
  </div>
  <div class="card-wrapper bottom">
    <div class="card-show">
      <div class="card-schedule">
        <div class="border-0 mb-4">
          <h4>More classes</h4>
          <%# <hr class="mt-0"> %>
        </div>
        <%# Class list start here %>
        <div class="card-class-show">
        <%= render 'studios/class_list', events: @events, events_group: @events_group %>
        </div>
        <%# class list end here %>
      </div>
    <%= render 'reviews/review_form' %>
    </div>
    <div class="card-show">
      <div class="card-show-infos">
        <div class="border-0 mb-4">
          <h4>Contact Us</h4>
          <%# <hr class="mt-0"> %>
        </div>
        <div class="card-event card-details">
          <%= link_to studio_path(@event.studio) do%>
          <%= cl_image_tag @event.studio.avatar.key%>
          <% end %>
          <div class="m-0">
          <p>Email : <%= @event.studio.email %> </p>
          <p> Phone : <%= @event.studio.phone_number %> </p>
          </div>
          <div class="icon-studio d-flex align-items-center m-2">
            <%= link_to studio_path(@event.studio) do%>
            <i class="fas fa-info-circle fa-2x"></i>
            <% end %>
            <button type="button" class="btn" data-action="click->popup#show">
              <i class="far fa-comments fa-2x"></i>
            </button>
          </div>
        </div>
        <div class="event-map mt-1">
          <%# <h4>Where to find us</h4> %>
          <%= render 'shared/map' %>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <% if @chatroom %>
      <%= render 'chatrooms/popup' %>
    <% end %>
  <% end %>
</div>