config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:create]
    post "/favourite", to: "events#favourite"
    delete "/unfavourite", to: "events#unfavourite"
  end

  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end

  resources :chatrooms, only: [:index, :show ] do
    resources :messages, only: :create
  end

  resources :studios, only: [:new, :show, :create, :edit, :update] do
    resources :events, only: [:create]
    resources :chatrooms, only: [:create]
  end

  get '/dashboard', to: 'pages#dashboard'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/pages/_dashboard_info_window.html.erb
<div class="card-map">
  <%= cl_image_tag studio.avatar.key, height: 40, width: 40, crop: :fill, class: "avatar-small" %>
  <h2><%= studio.name %></h2>
</div>

app/views/pages/dashboard.html.erb
<div class="container pt-4">
    <h2>Dashboard</h2>
    <div class="d-flex mt-3">
      <%= cl_image_tag current_user.avatar.key, class: "avatar-large" %>
      <div class="ms-4">
        <p class="m-0"><strong><%= current_user.first_name %> <%= current_user.last_name %></strong></p>
        <p class="m-0"><%= current_user.email %></p>
      </div>
    </div>
  <div class="card-dashboard d-flex">
  <div class="w-50">
    <div class="my-4">
      <h3>My Bookings</h3>
      <% @bookings_of_user.each do |booking_of_user| %>
        <div class="card-product mt-3">
          <%= cl_image_tag booking_of_user.event.photo.key %>
          <div class="card-product-body">
            <%= link_to event_path(booking_of_user.event) do %>
              <div class="card-product-infos">
                <h2><%= booking_of_user.event.name %></h2>
                <p>Date, Time: <%= booking_of_user.event.date.strftime("%e %b %Y") %> - <%= booking_of_user.event.time.strftime('%I:%M %p') %></p>
                <h3>Total Price: <strong><%= humanized_money_with_symbol(booking_of_user.amount) %></strong></h3>
              </div>
            <% end %>
            <div class="card-product-right">
              <% if booking_of_user.status == "Pending" %>
                <p class="text-secondary">
              <% elsif booking_of_user.status == "Paid" || booking_of_user.status == "Cash" %>
                <p class="text-success">
              <% elsif booking_of_user.status == "Cancelled" %>
                <p class="text-warning">
              <% end %>
                <%= booking_of_user.status %>
              </p>
              <div class="card-product-right-buttons">
              <% if booking_of_user.status != "Cancelled" %>
                <% if (booking_of_user.status == "Pending")%>
                  <%= link_to "Pay Now", new_booking_payment_path(booking_of_user) , class:"btn btn-secondary" %>
                <% elsif (booking_of_user.event.start_time >= Time.now())%>
                  <!-- Button Cancel Trigger Modal -->
                  <div>
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Cancel
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Cancel this class?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body d-flex justify-content-between">
                            <%= cl_image_tag booking_of_user.event.photo.key %>
                            <div class="card-product-infos">
                              <h2><%= booking_of_user.event.name %></h2>
                              <p>Date, Time: <%= booking_of_user.event.date.strftime("%e %b %Y") %> - <%= booking_of_user.event.time.strftime('%I:%M %p') %></p>
                              <p>Status: <%= booking_of_user.status %></p>
                              <h3>Total Price: <strong><%= humanized_money_with_symbol(booking_of_user.amount) %></strong></h3>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <div data-action="click->cancel-button#hide">
                            <%= link_to "Yes", booking_path(booking_of_user, { booking: {status: "Cancelled"} } ), method: :patch, class: "btn btn-primary"%>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- end of modal -->
                  <%# ---------- %>
                <% elsif booking_of_user.status != "Pending" %>
                  <div class="ms-2">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal-<%= booking_of_user.id%>" data-bs-whatever="@getbootstrap">
                      Review
                    </button>
                    <div class="modal fade" id="exampleModal-<%= booking_of_user.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Type your review for <%= booking_of_user.event.name %> </h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <%= simple_form_for [booking_of_user, @review], html: { id: "review-booking-#{booking_of_user.id}" } do |f| %>
                              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: { class: "review-book-form" } %>
                              <%= f.input :content, placeholder: "Min 20 character" %>
                            <% end %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" form="review-booking-<%= booking_of_user.id %>">Send Review</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="my-4">
      <h3>My Favorite Classes</h3>
      <% @favorited_events.each do |favorited_event| %>
        <div class="card-product mt-3 d-flex justify-content-between">
          <%= cl_image_tag favorited_event.photo.key %>
          <div class="card-product-infos">
            <%= link_to event_path(favorited_event) do %>
            <h2><%= favorited_event.name %></h2>
            <p>Date, Time: <%= favorited_event.date.strftime("%e %b %Y") %> - <%= favorited_event.time.strftime('%I:%M %p') %></p>
            <h3>Total Price: <strong><%= humanized_money_with_symbol(favorited_event.price) %></strong></h3>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div >
  <%# MAP %>
  <div class="card-dashboard-map w-50">
    <div class="my-4 position-sticky top-0">
    <h3>Get Ready For WOW ! </h3>
      <div class="mt-3 position-relative " >
        <%= render 'shared/map' %>
        <div id="instructions"></div>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "homepage.jpg" %>');">
  <div class="container d-flex flex-column align-items-center">
    <%= image_tag "wow-logo.png", class:"logo" %>
    <h1 class="text-center">First, find your sport.</h1>
    <%= form_tag events_path, method: :get do %>
      <div class="d-flex justify-content-center">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control banner-input me-2",
          placeholder: "Yoga, surfing, crossfit,..."
        %>
        <button class="btn btn-primary">Search</button>
      </div>
    <% end %>
    <div class="position-absolute bottom-0 start-50 translate-middle-x ">
      <a href="#scroll"><i class="fas fa-angle-down text-white fa-2x"></i></a>
    </div>
  </div>
</div>
<div class="container-category" id="scroll">
  <h3 class="quote text-center">
    What kind of sports will WOW you today?
  </h3>
  <div class="container text-center">
    <div class="cards-vertical">
      <% @categories.each do |category| %>
        <%= link_to events_path(category: category) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "#{category}.jpg" %>)">
            <%= category %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="container-reviews" style="margin-bottom: 100px;">
  <h3 class="text-center">Check out what customers have to say</h3>
    <%= render 'shared/card_review_large' %>
</div>