config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:create]
    post "/favourite", to: "events#favourite"
    delete "/unfavourite", to: "events#unfavourite"
  end

  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only: [:new, :create]
    resources :payments, only: :new
  end

  resources :chatrooms, only: [:index, :show ] do
    resources :messages, only: :create
  end

  resources :studios, only: [:new, :show, :create, :edit, :update] do
    resources :events, only: [:create]
    resources :chatrooms, only: [:create]
  end

  get '/dashboard', to: 'pages#dashboard'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_one_attached :avatar

  validates :address, :name, :email, :phone_number, :description, presence: true
  validates :user, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  def show
    @studio = Studio.find(params[:id])
    @events = Event.where(studio: @studio)
    @events_group = @events.group_by { |event| [event.date, event.time.strftime('%k:%M')] }.sort_by { |group| group[0] }
    @chatroom = Chatroom.find_by(user: current_user, studio: @studio)
    @message = Message.new # input form
    @markers = [{
        lat: @studio.latitude,
        lng: @studio.longitude,
        info_window: render_to_string(partial: "events/info_window", locals: { studio: @studio }, formats: [:html]),
        image_url: helpers.asset_url("wow-logo.png")
      }] # marker for the current studio
  end

  def new
    @studio = Studio.new
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.user = current_user
    if @studio.save
      redirect_to studio_path(@studio)
    else
     render 'new'
    end
  end

  private

  def studio_params
    params.require(:studio).permit(:name, :address, :email, :phone_number, :description, :avatar)
  end
end

app/views/studios/_class_list.html.erb
<div class="container class-list my-2">
  <% events_group.each do |date_time, events| %>
  <div class="card-events mb-4">
    <p class="mb-1"><%= date_time[0].strftime("%e %b %Y") %>, <%= date_time[1] %></p>
    <hr class="mt-0">
    <% events.each do |event| %>
      <%= link_to event_path(event) do  %>
        <div class="card-event mx-2">
          <%= cl_image_tag event.photo.key %>
          <div class="card-event-infos">
            <h2><%= event.name %></h2>
            <p><em>by <%= event.studio.name %></em></p>
            <p><i class="fas fa-user-friends"></i> <%= event.bookings.where.not(status: "Cancelled").count %> / <%= event.limit_attendees %></p>
            <p><%= event.level %> Class</p>
          </div>
          <div class="card-event-price">
            <strong><%= humanized_money_with_symbol(event.price) %></strong>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/studios/new.html.erb
<div class="container mb-5">
<h3>Create a Studio</h3>
<br>
<%= simple_form_for @studio do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :email %>
  <%= f.input :phone_number %>
  <%= f.input :description %>
  <%= f.input :avatar %>
  <%= f.submit class:"btn btn-primary" %>
<% end %>
</div>

app/views/studios/show.html.erb
<div class="container" id="studio-show" data-controller="popup">
  <button type="button" id="back" class="btn btn-primary"><%= link_to "Back", events_path %></button>
  <div class="card-wrapper-studio">
    <% if @studio.events.first.nil? %>
      <div class="card-studio-image" style="background-image: url('<%= image_path "gray-checkers.jpg", height: 400, crop: :fill %>')">
      </div>
    <% else %>
      <div class="card-studio-image" style="background-image: url('<%= cl_image_path @studio.events.first.photo.key, height: 400, crop: :fill %>')">
      </div>
    <% end %>
    <div class="card-show">
        <h2><%= @studio.name %></h2>
      <div>
        <span class="fa fa-star icon-star"></span>
        <span class="fa fa-star icon-star"></span>
        <span class="fa fa-star icon-star"></span>
        <span class="fa fa-star icon-empty"></span>
        <span class="fa fa-star icon-empty"></span>
      </div>
      <p><%= @studio.description %></p>
      <p>Email: <%= @studio.email %></p>
      <p>Phone number: <%= @studio.phone_number %></p>
      <div id="chat-btn">
        <% if @chatroom %>
          <button type="button" class="btn" data-action="click->popup#show">
            <i class="far fa-comments fa-2x"></i>
          </button>
        <% else %>
          <%= link_to studio_chatrooms_path(@studio), method: :post, class:"btn" do%>
            <i class="far fa-comments fa-2x"></i>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-wrapper-studio mt-5">
    <div class="card-schedule">
      <div class="border-0 mb-4">
        <h4>Schedule</h4>
        <%# <hr class="mt-0"> %>
      </div>
      <%= render 'class_list', events: @events, events_group: @events_group %>
    </div>
    <div class="card-membership">
      <div class="border-0 mb-4">
        <h4>Membership Plan</h4>
        <%# <hr class="mt-0"> %>
      </div>
      <div class="card-membership-package">
        <%= render 'shared/card_package' %>
      </div>
      <div class="studio-map mt-4">
        <h5>Where to find us</h5>
        <%= render 'shared/map' %>
      </div>
    </div>
  </div>
  <% if @chatroom %>
    <%= render 'chatrooms/popup' %>
  <% end %>
</div>